In [1]:
# python によるデータ分析の教科書　4.1Numpy
# 試したいのだけやってみる

In [8]:
import numpy as np
# 変形
c = np.array([1,2,3,4,5,6])
print(c)
c2 = c.reshape((2,3))
print(c2)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [10]:
c3 = c2.ravel()
c3

array([1, 2, 3, 4, 5, 6])

In [12]:
c4 = c2.flatten()
c4

array([1, 2, 3, 4, 5, 6])

In [14]:
# データ型
c.dtype

dtype('int64')

In [16]:
d = np.array([1,2] , dtype = np.int64)
d

array([1, 2])

In [17]:
d.dtype

dtype('int64')

In [19]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

In [20]:
c[0]

1

In [21]:
c[-1]

6

In [24]:
c[2:4]

array([3, 4])

In [25]:
c2[0]

array([1, 2, 3])

In [26]:
c2[1,1]

5

In [27]:
c2[:,0]

array([1, 4])

In [28]:
c2[1, :]

array([4, 5, 6])

In [31]:
c2[1,1] = 10
c2

array([[ 1,  2,  3],
       [ 4, 10,  6]])

In [32]:
c2[:, 2] = 11
c2

array([[ 1,  2, 11],
       [ 4, 10, 11]])

In [33]:
# 参照コピー
cc2 = c2
cc2

array([[ 1,  2, 11],
       [ 4, 10, 11]])

In [35]:
cc2[0,0] = 12
c2
cc2

array([[12,  2, 11],
       [ 4, 10, 11]])

In [36]:
cc2

array([[12,  2, 11],
       [ 4, 10, 11]])

In [37]:
# deepコピー
dc2 = c2.copy()
dc2[1,0] = 13
dc2

array([[12,  2, 11],
       [13, 10, 11]])

In [38]:
c2

array([[12,  2, 11],
       [ 4, 10, 11]])

In [41]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [43]:
np.arange(2, 20 ,3)

array([ 2,  5,  8, 11, 14, 17])

In [45]:
# 乱数
f = np.random.random((3, 2))
f

array([[0.82745104, 0.40722031],
       [0.60651461, 0.5222361 ],
       [0.45315036, 0.77966581]])

In [46]:
np.random.seed(123)
np.random.random((3,2))

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [47]:
np.random.rand(4,2)

array([[0.9807642 , 0.68482974],
       [0.4809319 , 0.39211752],
       [0.34317802, 0.72904971],
       [0.43857224, 0.0596779 ]])

In [48]:
np.random.randint(1,10)

1

In [49]:
np.random.randint(1,10,(3,4))

array([[1, 5, 2, 8],
       [4, 3, 5, 8],
       [3, 5, 9, 1]])

In [51]:
np.random.uniform(0.0, 10.9, size=(2,3))

array([[5.36372407, 8.06923066, 3.89924522],
       [4.54758843, 7.13646225, 4.07443555]])

In [62]:
np.random.randn(4,2)

array([[ 0.1073535 , -1.47942714],
       [-0.00946482,  0.20382859],
       [ 0.07444526, -1.964554  ],
       [ 0.94431723, -0.78457912]])

In [61]:
np.random.normal(10, 2, size=((2,3)))

array([[ 7.39531372, 10.24120614, 11.37509394],
       [ 9.34944362,  9.95244699,  7.32556051]])

In [63]:
# 行列
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [64]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [66]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
np.full((2,3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

In [68]:
np.array([1,3,np.nan])

array([ 1.,  3., nan])

In [69]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [71]:
l = np.array([1,1,2.3,4,10,40,3])
np.diff(l)

array([  0. ,   1.3,   1.7,   6. ,  30. , -37. ])

In [73]:
np.concatenate([c, l])

array([12. ,  2. , 11. ,  4. , 10. , 11. ,  1. ,  1. ,  2.3,  4. , 10. ,
       40. ,  3. ])

In [74]:
h = np.array([[1,1],[2,2],[3,3]])
h

array([[1, 1],
       [2, 2],
       [3, 3]])

In [75]:
h2 = np.array([[4],[5],[6]])
h2

array([[4],
       [5],
       [6]])

In [77]:
np.concatenate([h, h2], axis=1)

array([[1, 1, 4],
       [2, 2, 5],
       [3, 3, 6]])

In [78]:
np.hstack([h, h2])

array([[1, 1, 4],
       [2, 2, 5],
       [3, 3, 6]])

In [81]:
h3 = np.array([7,7])
h4 = np.vstack([h,h3])
h4

array([[1, 1],
       [2, 2],
       [3, 3],
       [7, 7]])

In [85]:
h5 , h6 = np.hsplit(h4, [1])
h5

array([[1],
       [2],
       [3],
       [7]])

In [86]:
h6

array([[1],
       [2],
       [3],
       [7]])

In [89]:
h7, h8 = np.vsplit(h4,[3])
h7

array([[1, 1],
       [2, 2],
       [3, 3]])

In [90]:
h8

array([[7, 7]])

In [91]:
h4.T

array([[1, 2, 3, 7],
       [1, 2, 3, 7]])

In [92]:
h4[np.newaxis, :]

array([[[1, 1],
        [2, 2],
        [3, 3],
        [7, 7]]])

In [93]:
h4[:,np.newaxis]

array([[[1, 1]],

       [[2, 2]],

       [[3, 3]],

       [[7, 7]]])

In [97]:
m = np.arange(0,4)
n = np.arange(5,8)
m

array([0, 1, 2, 3])

In [98]:
n

array([5, 6, 7])

In [99]:
x, y = np.meshgrid(m,n)
x

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [100]:
y

array([[5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]])

In [102]:
np.abs([1,-2,0, -100.001])

array([  1.   ,   2.   ,   0.   , 100.001])

In [107]:
np.sin([1, 0.5, 1/3])

array([0.84147098, 0.47942554, 0.3271947 ])

In [108]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [109]:
a + 10

array([11, 12, 13])

In [142]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [112]:
a+b

array([[2, 4, 6],
       [5, 7, 9]])

In [113]:
a1 = a[:, np.newaxis]
a1

array([[1],
       [2],
       [3]])

In [114]:
a + a1

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [115]:
np.mean(a + a1)

4.0

In [116]:
b * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [117]:
b **2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [118]:
b - a 

array([[0, 0, 0],
       [3, 3, 3]])

In [119]:
a * b

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [120]:
c = np.array([0,1,0])
c

array([0, 1, 0])

In [121]:
a/c

/Users/APP03-005/kouta/python/anaconda3/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf,  2., inf])

In [122]:
# 0除算の可能性がある場合、1e-6 (10^-6)の小さな値を足す
a/ (c + 1e-6)

array([1.000000e+06, 1.999998e+00, 3.000000e+06])

In [131]:
print(a)
np.shape(a)

[1 2 3]


(3,)

In [147]:
print(b)
np.shape(b)

[[1 2 3]
 [4 5 6]]


(2, 3)

In [133]:
a @ b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [143]:
b @ a

array([14, 32])

In [135]:
a > 2

array([False, False,  True])

In [145]:
b == 1

array([[ True, False, False],
       [False, False, False]])

In [146]:
np.count_nonzero(b > 3)

3

In [148]:
np.sum(b>2)

4

In [149]:
np.any(b > 2)

True

In [150]:
np.all(b > 2)

False

In [151]:
b[b > 2]

array([3, 4, 5, 6])

In [152]:
b == c

array([[False, False, False],
       [False, False, False]])

In [153]:
b == a

array([[ True,  True,  True],
       [False, False, False]])

In [154]:
(b == c) | (b == a)

array([[ True,  True,  True],
       [False, False, False]])

In [155]:
b[(b == c) | (b == a)]

array([1, 2, 3])

In [156]:
# 誤差の範囲内か検査する
np.allclose(b,c)

False

In [157]:
np.allclose(b,c, atol=10)

True

In [158]:
a.sum()

6